#include "cglp.h"

// Vircon32 port note: the original file registered all 42 games; this
// port includes only the games that have actually been ported so far (see
// the project README for the full list and how to add more). Add a
// forward declaration + call here for each additional game you port.
// Both blocks below are kept sorted by each game's actual display title
// (not its function name) so the in-game menu lists games alphabetically
// at runtime - see addGame()/getGame() in menu.c, which just walks the
// games[] array in registration order with no sorting of its own.
void addGameAccelb();
void addGameAerialBar();
void addGameAntLion();
void addGameArcfire();
void addGameAttackchain();
void addGameBBlast();
void addGameBCannon();
void addGameBmath();
void addGameBwalls();
void addGameBalance();
void addGameBallTour();
void addGameBalloon();
void addGameBallsBombs();
void addGameBamboo();
void addGameBargehop();
void addGameBaroll();
void addGameBaserunnerdash();
void addGameBladedancer();
void addGameBlastbuoy();
void addGameBlazethrust();
void addGameBlockstacker();
void addGameBoarding();
void addGameBolathread();
void addGameBombup();
void addGameBorecomet();
void addGameBottop();
void addGameBreedc();
void addGameBridgecross();
void addGameBsfish();
void addGameCNodes();
void addGameCTower();
void addGameCardq();
void addGameCastN();
void addGameCatapult();
void addGameCatchingwheel();
void addGameCateP();
void addGameChalkboard();
void addGameChargeBeam();
void addGameCirclew();
void addGameCleanrobo();
void addGameCleaner();
void addGameClinghop();
void addGameClockturret();
void addGameColorRoll();
void addGameCount();
void addGameCounterB();
void addGameCrossLine();
void addGameCuecrumb();
void addGameCywall();
void addGameDFight();
void addGameDLaser();
void addGameDmissile();
void addGameDpistols();
void addGameDango();
void addGameDarkCave();
void addGameDarksort();
void addGameDescents();
void addGameDivarr();
void addGameDoshin();
void addGameEarock();
void addGameEchobridge();
void addGameElastichero();
void addGameEmbattled();
void addGameFallbounce();
void addGameFeedingfrenzy();
void addGameFindastar();
void addGameFishgrill();
void addGameFlipo();
void addGameFlipbomb();
void addGameFloater();
void addGameFloors5();
void addGameFootlaser();
void addGameForfour();
void addGameFracave();
void addGameFromtwosides();
void addGameFroooog();
void addGameFuturewake();
void addGameGpress();
void addGameGtail();
void addGameGeocent();
void addGameGeoerase();
void addGameGeyserhop();
void addGameGhosthop();
void addGameGloop();
void addGameGolfme();
void addGameGrapplingH();
void addGameGraveler();
void addGameGravitybubble();
void addGameGravitydrift();
void addGameGravitywell();
void addGameGrenadier();
void addGameGrowth();
void addGameHexmin();
void addGameHitblowup();
void addGameHoardspout();
void addGameHoles();
void addGameHoppinhazards();
void addGameHoppingp();
void addGameHyperlaser();
void addGameIslash();
void addGameInTow();
void addGameInfrange();
void addGameInkinh();
void addGameInterspace();
void addGameInvincibleman();
void addGameJetstream();
void addGameJpaddle();
void addGameJugglingact();
void addGameJujump();
void addGameJumpon();
void addGameKelpclimber();
void addGameKite();
void addGameKitemaster();
void addGameKnightvspawns();
void addGameLrain();
void addGameLadderDrop();
void addGameLaserfortress();
void addGameLevitation();
void addGameLiedown();
void addGameLiftup();
void addGameLightdark();
void addGameLineb();
void addGameLland();
void addGameMfield();
void addGameMjamming();
void addGameMrider();
void addGameMagneticpendulum();
void addGameMakemaze();
void addGameMarblebounce();
void addGameMarusansi();
void addGameMeteoplanet();
void addGameMicrobialfocus();
void addGameMirrorfloor();
void addGameMissileguide();
void addGameMolen();
void addGameMonjum();
void addGameMonkeyt();
void addGameMortar();
void addGameNeonpollinator();
void addGameNotturn();
void addGameNsclimb();
void addGameNumberball();
void addGameNumberline();
void addGameOrbitgrazer();
void addGameOrbitman();
void addGameOutpostpatrol();
void addGamePfit();
void addGamePaintball();
void addGamePairsdrop();
void addGamePakuPaku();
void addGameParking();
void addGamePeriscopeping();
void addGamePhaserun();
void addGamePhotonline();
void addGamePileup();
void addGamePillars3d();
void addGamePinClimb();
void addGamePizzaarrow();
void addGamePlasmasplitter();
void addGamePodmigration();
void addGamePortalj();
void addGamePressm();
void addGamePressbound();
void addGamePulsepiper();
void addGamePulsestream();
void addGamePumppress();
void addGameQuantumleaper();
void addGameRring();
void addGameRWheel();
void addGameRaid();
void addGameRbdrive();
void addGameRebirth();
void addGameRecoilradar();
void addGameRefbals();
void addGameReflector();
void addGameRegene();
void addGameRevolvea();
void addGameRicochetpins();
void addGameRingblast();
void addGameRockettrail();
void addGameRolfrg();
void addGameRollhold();
void addGameRolls();
void addGameRollnrope();
void addGameRopecorral();
void addGameRotatingtunnel();
void addGameRotationrod();
void addGameRps();
void addGameSlanes();
void addGameSshake();
void addGameScaffold();
void addGameScrambird();
void addGameScreen();
void addGameShiny();
void addGameSighton();
void addGameSkyfloor();
void addGameSkygolf();
void addGameSkyraftsman();
void addGameSlalom();
void addGameSlashes();
void addGameSlimestretcher();
void addGameSmilyangry();
void addGameSmokeg();
void addGameSnake1();
void addGameSnaky();
void addGameSpearain();
void addGameSpincell();
void addGameSplitzig();
void addGameSquarebar();
void addGameStageseparation();
void addGameStareater();
void addGameStillfirechoir();
void addGameStompingbubbles();
void addGameStompshelter();
void addGameStormveil();
void addGameSubjump();
void addGameSumten();
void addGameSunflowersway();
void addGameSurvivor();
void addGameSwingby();
void addGameSwitchboard();
void addGameThanoi();
void addGameTlanes();
void addGameTlaser();
void addGameTpunch();
void addGameTapej();
void addGameTappump();
void addGameTarutobi();
void addGameTectonictether();
void addGameTeeter();
void addGameThrowm();
void addGameThrustlr();
void addGameThunder();
void addGameTilted();
void addGameTimberTest();
void addGameTonguehunter();
void addGameTornadotwister();
void addGameTotoge();
void addGameTrbeam();
void addGameTrojandefense();
void addGameTtfence();
void addGameTurbotunnel();
void addGameTurbulent();
void addGameTurtletide();
void addGameTwhols();
void addGameTwinjumpers();
void addGameTwinp();
void addGameTwofaced();
void addGameTwolane();
void addGameUdcave();
void addGameUnctrl();
void addGameUp1way();
void addGameUpdownpress();
void addGameUpshot();
void addGameVbomb();
void addGameVhwalls();
void addGameVineclimber();
void addGameWavybird();
void addGameWindpower();
void addGameWindrang();
void addGameWindowwasher();
void addGameWiper();
void addGameZartan();
void addGameZipfall();
void addGameZoneb();
void addGameZoomio();

void addGames() {
  addGameAccelb();
  addGameAerialBar();
  addGameAntLion();
  addGameArcfire();
  addGameAttackchain();
  addGameBBlast();
  addGameBCannon();
  addGameBmath();
  addGameBwalls();
  addGameBalance();
  addGameBallTour();
  addGameBalloon();
  addGameBallsBombs();
  addGameBamboo();
  addGameBargehop();
  addGameBaroll();
  addGameBaserunnerdash();
  addGameBladedancer();
  addGameBlastbuoy();
  addGameBlazethrust();
  addGameBlockstacker();
  addGameBoarding();
  addGameBolathread();
  addGameBombup();
  addGameBorecomet();
  addGameBottop();
  addGameBreedc();
  addGameBridgecross();
  addGameBsfish();
  addGameCNodes();
  addGameCTower();
  addGameCardq();
  addGameCastN();
  addGameCatapult();
  addGameCatchingwheel();
  addGameCateP();
  addGameChalkboard();
  addGameChargeBeam();
  addGameCirclew();
  addGameCleanrobo();
  addGameCleaner();
  addGameClinghop();
  addGameClockturret();
  addGameColorRoll();
  addGameCount();
  addGameCounterB();
  addGameCrossLine();
  addGameCuecrumb();
  addGameCywall();
  addGameDFight();
  addGameDLaser();
  addGameDmissile();
  addGameDpistols();
  addGameDango();
  addGameDarkCave();
  addGameDarksort();
  addGameDescents();
  addGameDivarr();
  addGameDoshin();
  addGameEarock();
  addGameEchobridge();
  addGameElastichero();
  addGameEmbattled();
  addGameFallbounce();
  addGameFeedingfrenzy();
  addGameFindastar();
  addGameFishgrill();
  addGameFlipo();
  addGameFlipbomb();
  addGameFloater();
  addGameFloors5();
  addGameFootlaser();
  addGameForfour();
  addGameFracave();
  addGameFromtwosides();
  addGameFroooog();
  addGameFuturewake();
  addGameGpress();
  addGameGtail();
  addGameGeocent();
  addGameGeoerase();
  addGameGeyserhop();
  addGameGhosthop();
  addGameGloop();
  addGameGolfme();
  addGameGrapplingH();
  addGameGraveler();
  addGameGravitybubble();
  addGameGravitydrift();
  addGameGravitywell();
  addGameGrenadier();
  addGameGrowth();
  addGameHexmin();
  addGameHitblowup();
  addGameHoardspout();
  addGameHoles();
  addGameHoppinhazards();
  addGameHoppingp();
  addGameHyperlaser();
  addGameIslash();
  addGameInTow();
  addGameInfrange();
  addGameInkinh();
  addGameInterspace();
  addGameInvincibleman();
  addGameJetstream();
  addGameJpaddle();
  addGameJugglingact();
  addGameJujump();
  addGameJumpon();
  addGameKelpclimber();
  addGameKite();
  addGameKitemaster();
  addGameKnightvspawns();
  addGameLrain();
  addGameLadderDrop();
  addGameLaserfortress();
  addGameLevitation();
  addGameLiedown();
  addGameLiftup();
  addGameLightdark();
  addGameLineb();
  addGameLland();
  addGameMfield();
  addGameMjamming();
  addGameMrider();
  addGameMagneticpendulum();
  addGameMakemaze();
  addGameMarblebounce();
  addGameMarusansi();
  addGameMeteoplanet();
  addGameMicrobialfocus();
  addGameMirrorfloor();
  addGameMissileguide();
  addGameMolen();
  addGameMonjum();
  addGameMonkeyt();
  addGameMortar();
  addGameNeonpollinator();
  addGameNotturn();
  addGameNsclimb();
  addGameNumberball();
  addGameNumberline();
  addGameOrbitgrazer();
  addGameOrbitman();
  addGameOutpostpatrol();
  addGamePfit();
  addGamePaintball();
  addGamePairsdrop();
  addGamePakuPaku();
  addGameParking();
  addGamePeriscopeping();
  addGamePhaserun();
  addGamePhotonline();
  addGamePileup();
  addGamePillars3d();
  addGamePinClimb();
  addGamePizzaarrow();
  addGamePlasmasplitter();
  addGamePodmigration();
  addGamePortalj();
  addGamePressm();
  addGamePressbound();
  addGamePulsepiper();
  addGamePulsestream();
  addGamePumppress();
  addGameQuantumleaper();
  addGameRring();
  addGameRWheel();
  addGameRaid();
  addGameRbdrive();
  addGameRebirth();
  addGameRecoilradar();
  addGameRefbals();
  addGameReflector();
  addGameRegene();
  addGameRevolvea();
  addGameRicochetpins();
  addGameRingblast();
  addGameRockettrail();
  addGameRolfrg();
  addGameRollhold();
  addGameRolls();
  addGameRollnrope();
  addGameRopecorral();
  addGameRotatingtunnel();
  addGameRotationrod();
  addGameRps();
  addGameSlanes();
  addGameSshake();
  addGameScaffold();
  addGameScrambird();
  addGameScreen();
  addGameShiny();
  addGameSighton();
  addGameSkyfloor();
  addGameSkygolf();
  addGameSkyraftsman();
  addGameSlalom();
  addGameSlashes();
  addGameSlimestretcher();
  addGameSmilyangry();
  addGameSmokeg();
  addGameSnake1();
  addGameSnaky();
  addGameSpearain();
  addGameSpincell();
  addGameSplitzig();
  addGameSquarebar();
  addGameStageseparation();
  addGameStareater();
  addGameStillfirechoir();
  addGameStompingbubbles();
  addGameStompshelter();
  addGameStormveil();
  addGameSubjump();
  addGameSumten();
  addGameSunflowersway();
  addGameSurvivor();
  addGameSwingby();
  addGameSwitchboard();
  addGameThanoi();
  addGameTlanes();
  addGameTlaser();
  addGameTpunch();
  addGameTapej();
  addGameTappump();
  addGameTarutobi();
  addGameTectonictether();
  addGameTeeter();
  addGameThrowm();
  addGameThrustlr();
  addGameThunder();
  addGameTilted();
  addGameTimberTest();
  addGameTonguehunter();
  addGameTornadotwister();
  addGameTotoge();
  addGameTrbeam();
  addGameTrojandefense();
  addGameTtfence();
  addGameTurbotunnel();
  addGameTurbulent();
  addGameTurtletide();
  addGameTwhols();
  addGameTwinjumpers();
  addGameTwinp();
  addGameTwofaced();
  addGameTwolane();
  addGameUdcave();
  addGameUnctrl();
  addGameUp1way();
  addGameUpdownpress();
  addGameUpshot();
  addGameVbomb();
  addGameVhwalls();
  addGameVineclimber();
  addGameWavybird();
  addGameWindpower();
  addGameWindrang();
  addGameWindowwasher();
  addGameWiper();
  addGameZartan();
  addGameZipfall();
  addGameZoneb();
  addGameZoomio();
}
